### ISSUE TITLE
Verify new PSD calculation

### ISSUE THREAD

**Issue by aringler-usgs** [reanthony-usgs/US_Noise_PSDs#12]
Rob,

Can you verify that the new PSD calculation is what we want?  I switched to cross-powers so that when the channels aren't equal we can get the phase.

**Comment by reanthony-usgs** [comment]
The PSDs generated from get_psds.py match my independent code to within 0.001 dB when I choose the same parameters. My code pulls the data and metadata locally as opposed to get_psds.py which grabs everything off IRIS.
